### ISSUE TITLE
does not work on node 0.12.0

### ISSUE THREAD

**Issue by alexander-rakov** [idobatter/node-win32ole#19]
Got an error like:

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified procedure could not be found.
appFolder\node_modules\win32ole\build\Release\node_win32ole.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (appFolder\node_modules\win32ole\lib\win32ole.js:3:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Its due to changing in node.js modules structure.

**Comment by dlbrown06** [comment]
+1

**Comment by yangpu** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by husky-dev** [comment]
+1

**Comment by WHenderson** [comment]
+1

**Comment by chintanp** [comment]
Kindly update the requirements for node version, node-gyp version, and supported OSes and platforms. 

Its not building on mine: node 0.12.1, Windows 7 64-bit, node-gyp v1.0.2

**Comment by yangpu** [comment]
Is anyone can help to improve the library on node.js v12?
