### ISSUE TITLE
Couldn't build.  Can you share build zip?

### ISSUE THREAD

**Issue by rajildavda** [idobatter/node-win32ole#24]
Can not build with VS#2015,  is it possible to get zip (only build) file that i can put directly into node_modules to be used in nodejs app?

C:\WORK\win32ole\node-win32ole>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.2.2 | win32 | x64
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\WORK\win32ole\node-win32ole\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\rajil\AppData\Roaming\npm\no
de_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\rajil\AppDat
a\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "build"
gyp ERR! cwd C:\WORK\win32ole\node-win32ole
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by fedevitch** [comment]
same problem

**Comment by ganluo960214** [comment]
Could not load the Visual C++ component "VCBuild.exe".

**Comment by ganluo960214** [comment]
your problem is up messages.

**Comment by generalov** [comment]
Try to install https://www.npmjs.com/package/windows-build-tools
